### ISSUE TITLE
Add support for OnePGT runs

### ISSUE THREAD

**Issue by andyb3** [moka-guys/automate_demultiplex#244]
OnePGT NextSeq runs will have pan number Pan2764. The script should:

1. Copy FASTQs to `/media/data1/share/agilent_OnePGT_uploads`
2. Test that the Agilent service connector software is running. Check the output of:
```sudo /opt/agilent/agilentserviceconnector status```
is
```agilentserviceconnector is running.```
If it's not running, restart:
```sudo /opt/agilent/agilentserviceconnector restart```
then run above test again. If it's still not running, send an alert to Slack
3. The run folder should be uploaded to DNAnexus (this is for back up only, they do not need to be run through a pipeline.)

**Comment by aledj2** [comment]
bump.
Need to create project
test fastq size (add alert)
upload using backup.py
copy to data1 (ensuring integrity)
check status of agilent connector (and alert)
