### ISSUE TITLE
Test for incorrect indexes in the samplesheet

### ISSUE THREAD

**Issue by aledj2** [moka-guys/automate_demultiplex#314]
if demultiplexing completed ok but the indexes were wrong may end up with missing fastqs. 
Can we test for this? Maybe check that all expected fastqs are present or maybe also check the filesizes are in an expected range (eg count the size of all fastqs and compare to undetermined?)

**Comment by RachelDuffin** [comment]
Still useful so leaving open - a check to stop any further processing to avoid having to re-process runs if the samplesheet was incorrect

**Comment by RachelDuffin** [comment]
Addressed in v45.0.0 - checking for incorrect indexes is not really feasible however a fastq validation step (gzip --test) has been added as well as a check to determine whether all fastqs are present
