### ISSUE TITLE
add dummy fastq file to allow pickup by workstation cleaner

### ISSUE THREAD

**Issue by rebeccahaines1** [moka-guys/automate_demultiplex#389]
The workstation cleaner is not removing TSO500 runfolders because there are no fastqs. Could create a dummy fastq file at this point to save in the runfolder, allowing it to be picked up by the workstation cleaner later.
https://github.com/moka-guys/automate_demultiplex/blob/873d592491f3fae360b3e122c373d2712209d4c3/upload_and_setoff_workflows.py#L355

**Comment by aledj2** [comment]
will update wscleaner instead
