### ISSUE TITLE
Name of TSO app in email

### ISSUE THREAD

**Issue by rebeccahaines1** [moka-guys/automate_demultiplex#406]
The config file now has the applet id rather than the app path for the TSO500 app. This is then used to name the workflow in the email sent with the SQL query, making it less clear for the duty bioinformatician what workflow has been run. Suggest adding a new variable in the config (~line 166) "tso500_app_name" and using this in the email here:
https://github.com/moka-guys/automate_demultiplex/blob/ad92b08bb00457760f66fc91c1b3e3b76d3460e1/upload_and_setoff_workflows.py#L2263

**Comment by aledj2** [comment]
done in #420
