### ISSUE TITLE
TSO500 logfiles uploaded to wrong location

### ISSUE THREAD

**Issue by rebeccahaines1** [moka-guys/automate_demultiplex#409]
The logfiles for TSO500 runs are uploaded to `dnanexusProject/runfolder/Logfiles` rather than `dnanexusProject/Logfiles` so they cannot be found by the workstation cleaner. The dx run commands file is correctly uploaded to `dnanexusProject/Logfiles`

**Comment by aledj2** [comment]
These files are output by the output parser. The logfiles used by the workstation cleaner appear to be in the expected location
