### ISSUE TITLE
add R numbers for all Pan

### ISSUE THREAD

**Issue by rebeccahaines1** [moka-guys/automate_demultiplex#410]
https://github.com/moka-guys/automate_demultiplex/blob/ad92b08bb00457760f66fc91c1b3e3b76d3460e1/automate_demultiplex_config.py#L360

In the panels list the StG Pan numbers mostly have the Rnumber as well as the panel "name" e.g. R208 BRCA2, but the viapath ones don't. Could the list be updated to make it clearer for the viewer which R number the pan is linked to? This issue arose during the IT outage when the lab wanted to check pan numbers for stg and viapath and there was no/limited access to Moka and geneworks

**Comment by aledj2** [comment]
doner in #5f2b574
