### ISSUE TITLE
tar creation is failing repeatedly

### ISSUE THREAD

**Issue by aledj2** [moka-guys/automate_demultiplex#454]
https://github.com/moka-guys/automate_demultiplex/blob/18f27965c4f853cbad08d3406833155202287a29/upload_and_setoff_workflows.py#L351

Currently this function is called up to 5 times, but it doesn't always seem to fix the issue.

I wonder if we could 
1) use a python package rather than subprocess and tar (not my favourite idea)
2) Only call it once. If it fails delete the tar and let the next iteration of the automated script try again - would need a way to limit the number of times it tried, and to keep a note of when each attempt was made so we can assess the logfiles.
3) Use something other than tar - would need to coordinate with a update to the tso500 app

**Comment by aledj2** [comment]
re point 3, could just use the backup runfolder script and not tar it at all - this happens as part of automated scripts anyway! issue would be in getting the data into the worker

**Comment by RachelDuffin** [comment]
Fixed in release https://github.com/moka-guys/automate_demultiplex/releases/tag/v44.3.7
