### ISSUE TITLE
upload agent test function

### ISSUE THREAD

**Issue by aledj2** [moka-guys/automate_demultiplex#98]
https://wiki.dnanexus.com/upload-Agent#Running-a-simple-diagnostic-test

**Comment by RachelDuffin** [comment]
We no longer use this

**Comment by RachelDuffin** [comment]
Closed as already implemented - see https://github.com/moka-guys/automate_demultiplex/blob/713d75a746f59525ff3beb88e18ff5fb103c16b1/upload_and_setoff_workflows.py#L337-L349
